# Generated by Django 5.0.6 on 2024-07-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactenquiry',
            old_name='websitelink',
            new_name='websitename',
        ),
    ]
